services:
  api:
    container_name: api
    build:
      context: .
      target: prod 
      dockerfile: apps/api/Dockerfile
    env_file:
      - ./apps/api/.env
    ports:
      - "3000:3000"

  www:
    container_name: www
    build:
      context: .
      target: prod
      dockerfile: apps/www/Dockerfile
    env_file:
      - ./apps/www/.env
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://$${HOSTNAME}:$${PORT}/health || exit 1"]
      start_period: 10s
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "3001:3001"

  www-e2e:
    container_name: www-e2e
    profiles: ["e2e"]
    environment:
      CI: "true"
    build:
      context: .
      target: prod
      dockerfile: apps/www/Dockerfile.e2e
    env_file:
      - ./apps/www/.env
    depends_on:
      www:
        condition: service_healthy

networks:
  default:
    name: loci
    driver: bridge
